name: Java CI/CD with Maven and Fly.io
on:
  push:
    branches: [ master, main ]  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' 
            java-version: '21'
            cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy app to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
